services:
  - type: web
    name: euphoria-backend
    env: node
    buildCommand: bun install && bun run build
    startCommand: bun run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: eupgorabd
          property: connectionString
    healthCheckPath: /
